"""
Django settings for suvapuli project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "6ip-days%@jrypf2ld8+f9+oc1#*2q86fqx206q8!1_6n8pey^"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "touglates.apps.TouglatesConfig",
    "django_filters",
    "django_filters_stoex.apps.DjangoFiltersStoexConfig",
    "tougshire_auth.apps.TougshireAuthConfig",
    "libtekin256",
    "libstaff256",
    "codabar_generator",
    "hotspot_insert_generator",
#    "spl_members.apps.SplMembersConfig",
#    "mifi_compare",
#    "spl_discoveries.apps.SplDiscoveriesConfig",
#    "spl_banlist.apps.SplBanlistConfig",
#    "spl_scheduler.apps.SplSchedulerConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "suvapuli.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "suvapuli/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "suvapuli.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


AUTH_USER_MODEL = "tougshire_auth.TougshireAuthUser"

TOUGSHIRE_AUTH_MENU_FILE = "suvapuli/menu.html"

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATICFILES_DIRS = [BASE_DIR / "suvapuli/static"]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LIBTEKIN = {
    "customfields":{
        "customfield01":{
            "label":"Serial Number",
            "help_text":"The Serial Number"
        },
        "customfield02":{
            "label":"Service ID",
            "help_text":"The Service Tag Number (Some mfrs use this as a alternative tserial number for service)"
        },
        "customfield03":{
            "label":"Phone Number",
            "help_text":"The Phone Number, for devices like phones and computers with mobile connectivity"
        },
        "customfield04":{
            "label":"IMEI",
            "help_text":"The IMEI, for devices like phones and computers with mobile connectivity"
        },
        "customfield05":{
            "label":"Asset Number",
            "help_text":"The asset number assigned by IT (usually on a City of Suffolk tag attached to the device)"
        },
        "customfield06":{
            "label":"Barcode",
            "help_text":"The network name ex \"LIBW10L-AB12345\""
        },
        "customfield07":{
            "label":"Network Name",
            "help_text":"The network name ex \"LIBW10L-AB12345\""
        },
        "customfield08":{
            "label":"Admin Password",
            "help_text":"The administrator password for this device"
        },
        "customfield09":{
            "label":"SSID",
            "help_text":"The SSID for access points"
        },
        "customfield10":{
            "label":"IP Address",
            "help_text":"The IP Address if static"
        },
        "customfield11":{
            "label":"Polaris Term/Pswd",
            "help_text":"The Polaris terminal name and password (ex sl-ts017/W0mb@t)"
        },
        "customfield00":{
            "label":"",
            "help_text":""
        },

    }
}

# PROJECT_INCLUDE_FILE = 'suvapuli/menu.html'
PROJECT_INCLUDE_FILES = {
    "main_menu": "suvapuli/menu.html",
    "main_css": "suvapuli/suvapuli.css",
}


DEFAULT_FROM_EMAIL = "suffolkpubliclibrary@tougshire.com"

HONEYPOT_FIELDS = {
    "spl_discoveries":{
        "InquiryForm":{
            "honeypota":{
                "label":"Grandfather's Maiden Name",
                "help_text":"Please enter your grandfather's maiden name",
            },
            "honeypotb":{
                "label":"Foot Address",
                "help_text":"Please enter the address of your foot",
            }

        }
    }
}
